---
apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: sse-api
  namespace: envoy-gateway-system
spec:
  apiName: sse-api
  apiType: "SSE"
  apiVersion: 1.0.0
  basePath: /sse/stream-1
  definitionPath: /api-definition
  organization: example-org
  production:
    - httpRouteRefs:
        - sse-http-route
  isDefaultVersion: false
  systemAPI: false