
---
apiVersion: v1
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    extensionManager:
      policyResources:
      # - group: example.extensions.io
      #   version: v1alpha1
      #   kind: API     
      # - group: dp.wso2.com 
      #   version: v1alpha3
      #   kind: API     
      # - group: example.extensions.io
      #   version: v1alpha1
      #   kind: API     
      resources:
      # - group: example.extensions.io
      #   version: v1alpha1
      #   kind: API 
      # - group: dp.wso2.com 
      #   version: v1alpha1
      #   kind: API
      - group: dp.wso2.com 
        version: v1alpha2
        kind: API  
      # - group: dp.wso2.com 
      #   version: v1alpha3
      #   kind: API                
      hooks:
        xdsTranslator:
          post:
          - HTTPListener
          - Route
      service:
        fqdn: 
          hostname: extension-server.envoy-gateway-system.svc.cluster.local
          port: 5005
    provider:
      kubernetes:
        rateLimitDeployment:
          container:
            image: docker.io/envoyproxy/ratelimit:49af5cca
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                    - imagePullPolicy: IfNotPresent
                      name: envoy-ratelimit
        shutdownManager:
          image: docker.io/envoyproxy/gateway:v1.2.2
      type: Kubernetes
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
